import { emptyDesign } from "@/core/design";
import type { BrandProfile, ProjectConfig, StudioPost } from "@/core/types";

const sora =
  'var(--font-sora), Sora, Helvetica Neue, Helvetica, Arial, sans-serif';

const TEXTURE = "/projects/offerhub/textures/gradient.png";

export const offerhubBrand: BrandProfile = {
  name: "OFFER-HUB",
  shortName: "OFFER-HUB",
  description:
    "OFFER-HUB is a freelance marketplace connecting businesses with skilled freelancers worldwide — with tools to find talent, collaborate, and pay securely.",
  tagline: "Find talent. Hire smart. Grow your business.",
  website: "https://www.offer-hub.org/",
  colors: [
    { id: "navy", name: "Navy", hex: "#19213D" },
    { id: "teal", name: "Teal", hex: "#149A9B" },
    { id: "white", name: "White", hex: "#F1F3F7" },
    { id: "slate", name: "Slate Gray", hex: "#6D758F" },
  ],
  logos: [
    {
      id: "primary",
      name: "Primary mark",
      src: "/projects/offerhub/logos/mark-color.png",
      role: "primary",
    },
    {
      id: "isotipo",
      name: "Mark",
      src: "/projects/offerhub/logos/mark-color.png",
      role: "isotipo",
    },
    {
      id: "light",
      name: "Light mark",
      src: "/projects/offerhub/logos/mark-light.png",
      role: "light",
    },
    {
      id: "wordmark",
      name: "Wordmark",
      src: "/projects/offerhub/logos/wordmark-color.png",
      role: "wordmark",
    },
    {
      id: "logo-primary-alt",
      name: "Primary (alt)",
      src: "/projects/offerhub/logos/logo-primary.png",
      role: "secondary",
    },
    {
      id: "logo-light-alt",
      name: "Light (alt)",
      src: "/projects/offerhub/logos/logo-light.png",
      role: "dark",
    },
  ],
  fonts: {
    primary: sora,
    secondary: sora,
    display: sora,
    body: sora,
  },
  defaultBackground: "navy",
  defaultText: "white",
  defaultAccent: "teal",
};

const d = (partial: Parameters<typeof emptyDesign>[1]) =>
  emptyDesign(offerhubBrand, {
    textureSrc: TEXTURE,
    textureVisible: true,
    textureScale: 1,
    textureOpacity: 1,
    textureRotation: 0,
    textureBlur: 0,
    ...partial,
  });

const posts: StudioPost[] = [
  {
    id: "01",
    baseId: "01",
    number: "01",
    title: "What is OFFER-HUB?",
    exportKind: "jpg",
    exportSlug: "01-brand",
    durationMs: 0,
    status: "active",
    kind: "single",
    template: "oh-brand-intro",
    design: d({
      eyebrow: "01 / GLOBAL WORK",
      headline: "WORK\nWITHOUT\nBORDERS.",
      supporting:
        "OFFER-HUB connects businesses with skilled freelancers worldwide — with tools to find talent, collaborate and pay securely.",
      cta: "FIND TALENT · HIRE SMART",
      background: "navy",
      text: "white",
      accent: "teal",
      showLogo: true,
      logoPosition: "top-left",
      textureVisible: true,
      textureScale: 1.35,
      textureRotation: -18,
      textureOpacity: 0.95,
      textureBlur: 0,
      pathScale: 1.1,
      pathX: 20,
      pathY: 0,
    }),
  },
  {
    id: "02",
    baseId: "02",
    number: "02",
    title: "A new way to freelance",
    exportKind: "gif",
    exportSlug: "02-freelancing",
    durationMs: 5500,
    status: "active",
    kind: "single",
    template: "oh-compare",
    design: d({
      eyebrow: "02 / FREELANCING",
      headline: "LESS FRICTION.\nMORE WORK.",
      supporting: "Freelancing shouldn't come with borders, friction and unnecessary fees.",
      labels: ["Global collaboration", "Secure payments", "Direct communication"],
      background: "white",
      text: "navy",
      accent: "teal",
      showLogo: true,
      logoPosition: "top-left",
      textureVisible: true,
      textureScale: 1.2,
      textureOpacity: 0.9,
      textureX: 80,
      textureY: -40,
      animationEnabled: true,
    }),
  },
  {
    id: "03",
    baseId: "03",
    number: "03",
    title: "International payments",
    exportKind: "jpg",
    exportSlug: "03-payments",
    durationMs: 0,
    status: "active",
    kind: "single",
    template: "oh-payments",
    design: d({
      eyebrow: "03 / PAYMENTS",
      headline: "YOUR WORK\nIS GLOBAL.\nYOUR PAYMENTS\nSHOULD BE TOO.",
      supporting:
        "Send payments to freelancers worldwide with zero transfer fees through OFFER-HUB.",
      cta: "POWERED BY STELLAR",
      background: "white",
      text: "navy",
      accent: "teal",
      showLogo: true,
      logoPosition: "top-left",
      imageSrc: "/projects/offerhub/photography/desk.png",
      imageObjectX: 40,
      imageObjectY: 35,
      imageZoom: 1.2,
      overlayColor: "white",
      overlayIntensity: 0.55,
      textureVisible: true,
      textureScale: 1.4,
      textureX: 120,
      textureY: 200,
      textureOpacity: 0.95,
      textureRotation: 12,
      pathScale: 1,
    }),
  },
  {
    id: "04",
    baseId: "04",
    number: "04",
    title: "Escrow",
    exportKind: "gif",
    exportSlug: "04-escrow",
    durationMs: 6500,
    status: "active",
    kind: "single",
    template: "oh-escrow",
    design: d({
      eyebrow: "04 / ESCROW",
      headline: "WORK\nWITH\nTRUST.",
      supporting: "Escrow helps protect both sides — funds secured until work is approved.",
      labels: ["Client", "Funds secured", "Work delivered", "Approval", "Freelancer paid"],
      background: "navy",
      text: "white",
      accent: "teal",
      showLogo: true,
      logoPosition: "top-left",
      textureVisible: true,
      textureScale: 1.5,
      textureOpacity: 0.55,
      textureRotation: 90,
      textureBlur: 2,
      animationEnabled: true,
    }),
  },
  {
    id: "05",
    baseId: "05",
    number: "05",
    title: "Why we built OFFER-HUB",
    exportKind: "jpg",
    exportSlug: "05-why-we-built",
    durationMs: 0,
    status: "active",
    kind: "single",
    template: "oh-editorial",
    design: d({
      eyebrow: "05 / WHY WE BUILD",
      headline: "TALENT\nIS EVERYWHERE.\nOPPORTUNITY\nSHOULD BE TOO.",
      supporting:
        "We're building OFFER-HUB to make it easier for freelancers and businesses to find each other, work together and move money across borders with confidence.",
      cta: "WHERE TALENT MEETS OPPORTUNITY",
      background: "navy",
      text: "white",
      accent: "teal",
      showLogo: true,
      logoPosition: "top-left",
      imageSrc: "/projects/offerhub/photography/talent.png",
      imageObjectX: 48,
      imageObjectY: 28,
      imageZoom: 1.15,
      overlayColor: "navy",
      overlayIntensity: 0.72,
      textureVisible: true,
      textureScale: 1.1,
      textureOpacity: 0.65,
      textureX: -40,
      textureY: -60,
      textureRotation: -8,
    }),
  },
  {
    id: "06",
    baseId: "06",
    number: "06",
    title: "Why Stellar",
    exportKind: "jpg",
    exportSlug: "06-stellar",
    durationMs: 0,
    status: "active",
    kind: "single",
    template: "oh-ecosystem",
    design: d({
      eyebrow: "06 / INFRASTRUCTURE",
      headline: "GLOBAL WORK\nNEEDS GLOBAL\nINFRASTRUCTURE.",
      supporting: "Why Stellar?",
      labels: [
        "Fast settlement",
        "Low-cost transactions",
        "Built for cross-border value",
      ],
      cta: "BUILT ON STELLAR",
      background: "navy",
      text: "white",
      accent: "teal",
      showLogo: true,
      logoPosition: "top-left",
      textureVisible: true,
      textureScale: 1.6,
      textureOpacity: 0.9,
      textureRotation: 24,
      textureX: 100,
      textureY: -80,
      pathScale: 1.05,
      pathX: 40,
      pathY: -20,
    }),
  },
  {
    id: "07",
    baseId: "07",
    number: "07",
    title: "Early access / CTA",
    exportKind: "jpg",
    exportSlug: "07-cta",
    durationMs: 0,
    status: "active",
    kind: "single",
    template: "oh-cta",
    design: d({
      eyebrow: "07 / START",
      headline: "YOUR NEXT\nOPPORTUNITY\nCOULD BE\nANYWHERE.",
      supporting: "Join OFFER-HUB and be part of a marketplace built for global work.",
      cta: "Join OFFER-HUB",
      background: "white",
      text: "navy",
      accent: "teal",
      showLogo: true,
      logoPosition: "top-left",
      imageSrc: "/projects/offerhub/photography/remote.png",
      imageObjectX: 55,
      imageObjectY: 30,
      imageZoom: 1.25,
      overlayColor: "white",
      overlayIntensity: 0.35,
      textureVisible: true,
      textureScale: 1.3,
      textureOpacity: 0.55,
      textureRotation: -12,
      textureBlur: 4,
    }),
  },
  {
    id: "08",
    baseId: "08",
    number: "08",
    title: "Product in motion",
    exportKind: "gif",
    exportSlug: "08-product",
    durationMs: 5500,
    status: "active",
    kind: "single",
    template: "oh-product",
    design: d({
      eyebrow: "08 / PRODUCT",
      headline: "BUILT FOR\nINDEPENDENT\nWORK.",
      labels: ["Browse talent", "Review offer", "Collaborate", "Secure payment"],
      background: "white",
      text: "navy",
      accent: "teal",
      showLogo: true,
      logoPosition: "top-right",
      imageSrc: "/projects/offerhub/ui/og-hero.png",
      imageZoom: 1.1,
      textureVisible: true,
      textureScale: 1.2,
      textureOpacity: 0.85,
      textureY: -100,
      animationEnabled: true,
    }),
  },
  {
    id: "09",
    baseId: "09",
    number: "09",
    title: "Reputation / future of work",
    exportKind: "gif",
    exportSlug: "09-reputation",
    durationMs: 6000,
    status: "active",
    kind: "single",
    template: "oh-reputation",
    design: d({
      eyebrow: "09 / STORY",
      headline: "YOUR WORK\nBUILDS YOUR\nSTORY.",
      supporting: "Every project is part of your professional story.",
      cta: "Build your reputation through real work.",
      labels: ["Identity", "Launch", "Systems", "Growth", "Delivery"],
      background: "navy",
      text: "white",
      accent: "teal",
      showLogo: true,
      logoPosition: "top-left",
      textureVisible: true,
      textureScale: 1.4,
      textureOpacity: 0.5,
      textureY: 180,
      textureBlur: 6,
      animationEnabled: true,
    }),
  },
];

export const offerhubProject: ProjectConfig = {
  id: "offerhub",
  name: "OFFER-HUB",
  seeded: true,
  createdAt: "2026-08-27",
  formatId: "instagram-portrait",
  exportPrefix: "offerhub",
  campaign: "September 2026 — Foundations",
  brand: offerhubBrand,
  assets: [
    {
      id: "texture",
      name: "Campaign texture",
      src: "/offerhub_texture.png",
      category: "textures",
      tags: ["gradient", "teal", "navy", "signature"],
    },
    {
      id: "gradient",
      name: "Texture · gradient",
      src: "/projects/offerhub/textures/gradient.png",
      category: "textures",
      tags: ["gradient", "campaign"],
    },
    {
      id: "photo-remote",
      name: "Remote work",
      src: "/projects/offerhub/photography/remote.png",
      category: "photography",
      tags: ["editorial", "freelancer"],
    },
    {
      id: "photo-talent",
      name: "Talent portrait",
      src: "/projects/offerhub/photography/talent.png",
      category: "photography",
      tags: ["editorial", "portrait"],
    },
    {
      id: "photo-desk",
      name: "Desk / workspace",
      src: "/projects/offerhub/photography/desk.png",
      category: "photography",
      tags: ["editorial", "workspace"],
    },
    {
      id: "mark-color",
      name: "Mark · color",
      src: "/projects/offerhub/logos/mark-color.png",
      category: "logos",
      tags: ["mark", "official"],
    },
    {
      id: "mark-light",
      name: "Mark · light",
      src: "/projects/offerhub/logos/mark-light.png",
      category: "logos",
      tags: ["mark", "light", "official"],
    },
    {
      id: "wordmark-color",
      name: "Wordmark · color",
      src: "/projects/offerhub/logos/wordmark-color.png",
      category: "logos",
      tags: ["wordmark"],
    },
    {
      id: "wordmark-light",
      name: "Wordmark · light",
      src: "/projects/offerhub/logos/wordmark-light.png",
      category: "logos",
      tags: ["wordmark", "light"],
    },
    {
      id: "logo-primary",
      name: "Logo primary (alt)",
      src: "/projects/offerhub/logos/logo-primary.png",
      category: "logos",
      tags: ["mark", "alt"],
    },
    {
      id: "logo-light",
      name: "Logo light (alt)",
      src: "/projects/offerhub/logos/logo-light.png",
      category: "logos",
      tags: ["mark", "light", "alt"],
    },
    {
      id: "stellar",
      name: "Stellar",
      src: "/projects/offerhub/icons/stellar.png",
      category: "icons",
      tags: ["stellar"],
    },
    {
      id: "stellar-icon",
      name: "Stellar icon",
      src: "/projects/offerhub/icons/stellar-icon.png",
      category: "icons",
      tags: ["stellar"],
    },
    {
      id: "og-hero",
      name: "Product UI board",
      src: "/projects/offerhub/ui/og-hero.png",
      category: "ui",
      tags: ["product", "ui"],
    },
  ],
  posts,
  graphics: {
    paths: {
      connectSpark: "M160 1180C320 1100 480 980 640 920C780 860 880 900 980 840",
      paymentPath: "M160 980C320 920 480 1040 640 980C800 920 860 1040 920 980",
      orbit: "M620 220C740 180 980 220 1020 360C1060 520 900 560 780 480C660 400 700 280 620 220",
      agreement: "M200 720C360 680 480 760 620 720C760 680 860 760 980 700",
      match: "M140 900C300 820 420 780 540 760C700 730 820 780 980 720",
    },
  },
};
