import { emptyDesign } from "@/core/design";
import type { BrandProfile, ProjectConfig, StudioPost } from "@/core/types";

const geist =
  'var(--font-geist-sans), Helvetica Neue, Helvetica, Arial, sans-serif';

export const sendaBrand: BrandProfile = {
  name: "Senda",
  shortName: "senda",
  description:
    "Senda helps organizations track how resources move, how they are used and what they make possible.",
  tagline: "See the path. See the impact.",
  website: "https://github.com/SendaLabs/senda-landing",
  colors: [
    { id: "forest", name: "Forest", hex: "#173F35" },
    { id: "cream", name: "Cream", hex: "#F4F1E8" },
    { id: "lime", name: "Lime", hex: "#B7E46C" },
    { id: "burgundy", name: "Burgundy", hex: "#401A25" },
    { id: "stone", name: "Stone", hex: "#D9D5CA" },
    { id: "charcoal", name: "Charcoal", hex: "#171918" },
  ],
  logos: [
    {
      id: "isotipo",
      name: "Isotipo",
      src: "/projects/senda/logos/isotipo.png",
      role: "isotipo",
    },
    {
      id: "wordmark-asset",
      name: "Wordmark asset",
      src: "/projects/senda/logos/wordmark.png",
      role: "wordmark",
    },
    {
      id: "primary",
      name: "Primary mark",
      src: "/projects/senda/logos/isotipo.png",
      role: "primary",
    },
  ],
  fonts: {
    primary: geist,
    secondary: geist,
    display: geist,
    body: geist,
  },
  defaultBackground: "forest",
  defaultText: "cream",
  defaultAccent: "lime",
};

const d = (partial: Parameters<typeof emptyDesign>[1]) =>
  emptyDesign(sendaBrand, partial);

const whoIntro = d({
  headline: "Who we are.",
  supporting: "Building a clearer path for social funding.",
  background: "burgundy",
  text: "cream",
  accent: "cream",
  showLogo: true,
  showMark: true,
  logoMode: "isotipo",
  logoColor: "cream",
  pathVisible: false,
});

const posts: StudioPost[] = [
  {
    id: "01",
    baseId: "01",
    number: "01",
    title: "Brand introduction",
    exportKind: "jpg",
    durationMs: 0,
    status: "active",
    kind: "single",
    template: "brand-intro",
    design: d({
      headline: "senda",
      supporting: "See the path.\nSee the impact.",
      showMark: true,
      pathVisible: true,
      pathId: "introTick",
      pathColor: "lime",
      pathWidth: 1.6,
    }),
  },
  {
    id: "02",
    baseId: "02",
    number: "02",
    title: "Brand idea",
    exportKind: "gif",
    durationMs: 6000,
    status: "active",
    kind: "single",
    template: "brand-idea",
    design: d({
      headline: "Every resource\nhas a path.",
      supporting: "We make it visible.",
      background: "cream",
      text: "forest",
      accent: "lime",
      logoMode: "wordmark",
      logoColor: "forest",
      pathVisible: true,
      pathId: "idea",
      pathColor: "lime",
      pathWidth: 2.4,
    }),
  },
  {
    id: "03",
    baseId: "03",
    number: "03",
    title: "The problem",
    exportKind: "gif",
    durationMs: 6500,
    status: "active",
    kind: "single",
    template: "problem",
    design: d({
      eyebrow: "The missing stretch",
      headline: "What happens after\nfunding is sent?",
      labels: ["Receipt", "Spreadsheet", "Photo", "Report", "Expense"],
      background: "cream",
      text: "forest",
      showLogo: false,
      pathVisible: true,
      pathId: "connect",
      pathColor: "lime",
    }),
  },
  {
    id: "04",
    baseId: "04",
    number: "04",
    title: "How Senda works",
    exportKind: "gif",
    durationMs: 7000,
    status: "active",
    kind: "single",
    template: "how-it-works",
    design: d({
      eyebrow: "How it works",
      labels: ["Funding", "Project", "Expense", "Evidence", "Impact"],
      logoMode: "wordmark",
      logoPosition: "top-right",
      pathVisible: true,
      pathId: "journey",
      pathColor: "lime",
    }),
  },
  {
    id: "05",
    baseId: "05",
    number: "05",
    title: "Follow what matters",
    exportKind: "jpg",
    durationMs: 0,
    status: "active",
    kind: "single",
    template: "follow",
    design: d({
      headline: "Follow\nwhat matters.",
      logoMode: "wordmark",
      logoPosition: "bottom-right",
      imageSrc: "/projects/senda/photography/field.jpg",
      overlayColor: "forest",
      overlayIntensity: 0.78,
      pathVisible: true,
      pathId: "photo",
      pathColor: "lime",
      pathWidth: 1.8,
    }),
  },
  {
    id: "06",
    baseId: "06",
    number: "06",
    title: "Product value",
    exportKind: "jpg",
    durationMs: 0,
    status: "active",
    kind: "single",
    template: "product-value",
    design: d({
      headline: "Less reporting.\nMore clarity.",
      supporting: "Keep funding, execution and evidence connected.",
      background: "cream",
      text: "forest",
      logoColor: "forest",
      logoPosition: "top-right",
    }),
  },
  {
    id: "07",
    baseId: "07",
    number: "07",
    title: "Who we are",
    exportKind: "jpg",
    durationMs: 0,
    status: "active",
    kind: "carousel",
    template: "who-intro",
    design: whoIntro,
    slides: [
      { id: "who-01", template: "who-intro", title: "Introduction", design: whoIntro },
      {
        id: "who-02",
        template: "who-why",
        title: "Why Senda exists",
        design: d({
          headline: "Transparency shouldn't create more work.",
          supporting:
            "Social-impact teams often manage funding, execution, evidence and reporting across disconnected tools.\n\nSenda is being built to bring that journey into one clearer place.",
          background: "cream",
          text: "forest",
          accent: "forest",
          showLogo: false,
          pathVisible: true,
          pathId: "idea",
          pathColor: "forest",
          pathWidth: 1.4,
        }),
      },
      {
        id: "who-03",
        template: "who-believe",
        title: "What we believe",
        design: d({
          headline:
            "We believe clarity should strengthen organizations, not slow them down.",
          labels: [
            "Human first",
            "Technology should adapt to the way people already work.",
            "Clear by default",
            "Information should be understandable without needing technical knowledge.",
            "Built for trust",
            "Evidence and accountability should be part of the process, not something reconstructed later.",
          ],
          background: "cream",
          text: "forest",
          accent: "burgundy",
          showLogo: false,
        }),
      },
      {
        id: "who-04",
        template: "who-team",
        title: "The team",
        design: d({
          eyebrow: "The team",
          headline: "A small team, a clearer path.",
          supporting: "Costa Rica · Argentina",
          labels: [
            "Emilio Alfaro",
            "Product / Strategy",
            "Delfina Corradini",
            "Engineering / Technology",
          ],
          logoMode: "wordmark",
          logoPosition: "top-right",
        }),
      },
      {
        id: "who-05",
        template: "who-close",
        title: "Follow what matters",
        design: d({
          headline: "Follow what matters.",
          supporting: "See the path.\nSee the impact.",
          showLogo: false,
          showMark: true,
          pathVisible: true,
          pathId: "cta",
          pathColor: "lime",
          pathWidth: 1.8,
        }),
      },
    ],
  },
  {
    id: "08",
    baseId: "08",
    number: "08",
    title: "Brand / CTA",
    exportKind: "jpg",
    durationMs: 0,
    status: "active",
    kind: "single",
    template: "brand-cta",
    design: d({
      headline: "See where resources go.\nSee what they make possible.",
      cta: "Follow the change.",
      showMark: true,
      logoMode: "wordmark",
      logoPosition: "bottom-left",
      pathVisible: true,
      pathId: "cta",
      pathColor: "lime",
      pathWidth: 1.8,
    }),
  },
  {
    id: "01A",
    baseId: "01",
    number: "01A",
    title: "Brand introduction · Burgundy",
    exportKind: "jpg",
    durationMs: 0,
    status: "draft",
    kind: "single",
    variantOf: "01",
    variantLabel: "01A",
    template: "brand-intro",
    design: d({
      headline: "senda",
      supporting: "See the path.\nSee the impact.",
      background: "burgundy",
      accent: "cream",
      showMark: true,
      logoColor: "cream",
      pathVisible: true,
      pathId: "introTick",
      pathColor: "cream",
      pathWidth: 1.4,
    }),
  },
  {
    id: "05A",
    baseId: "05",
    number: "05A",
    title: "Follow what matters · Burgundy",
    exportKind: "jpg",
    durationMs: 0,
    status: "draft",
    kind: "single",
    variantOf: "05",
    variantLabel: "05A",
    template: "follow",
    design: d({
      headline: "Follow\nwhat matters.",
      background: "burgundy",
      accent: "cream",
      logoMode: "wordmark",
      logoColor: "cream",
      logoPosition: "bottom-right",
      imageSrc: "/projects/senda/photography/field.jpg",
      overlayColor: "burgundy",
      overlayIntensity: 0.58,
      pathVisible: true,
      pathId: "photo",
      pathColor: "cream",
      pathWidth: 1.6,
    }),
  },
];

export const sendaProject: ProjectConfig = {
  id: "senda",
  name: "Senda",
  seeded: true,
  createdAt: "2026-08-24",
  formatId: "instagram-portrait",
  exportPrefix: "senda",
  brand: sendaBrand,
  assets: [
    { id: "isotipo", name: "Isotipo", src: "/projects/senda/logos/isotipo.png", category: "logos", tags: ["mark"] },
    { id: "wordmark", name: "Wordmark", src: "/projects/senda/logos/wordmark.png", category: "logos", tags: ["logo"] },
    { id: "field", name: "Field", src: "/projects/senda/photography/field.jpg", category: "photography", tags: ["documentary"] },
    { id: "forest", name: "Forest", src: "/projects/senda/photography/forest.jpg", category: "photography", tags: ["nature"] },
    { id: "classroom", name: "Classroom", src: "/projects/senda/photography/classroom.jpg", category: "photography", tags: ["education"] },
    { id: "education", name: "Education", src: "/projects/senda/photography/education.jpg", category: "photography", tags: ["education"] },
    { id: "community", name: "Community", src: "/projects/senda/photography/community.jpg", category: "photography", tags: ["people"] },
    { id: "receipt", name: "Receipt fragment", src: "/projects/senda/ui/receipt.jpg", category: "ui", tags: ["product"] },
  ],
  posts,
  graphics: {
    paths: {
      introTick: "M720 1180C840 1080 940 980 1040 860",
      idea: "M-40 1180C180 1080 280 760 480 640C700 500 820 720 980 560C1100 440 1040 220 1180 80",
      connect: "M160 420C280 460 340 560 420 640C520 740 560 820 640 900C740 1000 820 1080 960 1160",
      journey: "M540 220C470 390 610 530 540 680C470 840 610 990 540 1220",
      photo: "M-80 1100C200 980 360 760 560 700C800 630 920 860 1180 780",
      cta: "M-120 280C80 200 240 360 420 240C640 80 760 320 980 180C1120 80 1180 260 1280 120",
    },
  },
};
